### ISSUE TITLE
Optional keys in templates

### ISSUE THREAD

**Issue by mkolar** [4degrees/lucidity#29]
Hey.

It would be very useful to be able to have a way of specifying optional keys in templates. 

for instace `{shot}/{task}/{shot}_{task}_{version}[_{comment].ma` would resolve whether `comment` is present in the data or not. It would of course result in `sh010/anim/sh010_anim_v01_myComment.ma` vs `sh010/anim/sh010_anim_v01.ma`

It could easily work for more flexible directories too.`[{parent1}/][{parent2}/][{parent3}/]{shot}/{task}`. I know this is already possible with custom regex, however it's certainly less straight forward.

**Comment by martinpengellyphillips** [comment]
My thought on this was to just have lots of templates in a collection and use the batch parse methods (and in future template collection methods) to iterate through and find best match (#18). If necessary other code can generate the variations.

My concern with introducing optional keys is it may become complex and confusing quite quickly. The goal of Lucidity is to provide a helper layer above regexes, but if we implement too much logic into the parser then you might as well just use regexes.

Happy to be convinced otherwise though!
